name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    strategy:
      matrix:
        lambdafiles: [bar,baz,foo]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i
        
      - name: Build
        run: npm run build

      - name: Move node_modules to dist
        run: mv node_modules dist/node_modules

      - name: Zip
        run: (cd dist && zip -r ../${{ matrix.lambdafiles }}.zip ${{ matrix.lambdafiles }}.js)

      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GITHUB_ACTION_LAMBDA
          aws-region: ${{ secrets.AWS_REGION }}
          function_name: ${{ matrix.lambdafiles }}
          zip_file: ${{ matrix.lambdafiles }}.zip