name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        lambdafiles: [createBusiness,getBusinessStockholders,getBusinesses,getMarketStocks,getUserStocks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: github_lambda_deploy_${{ matrix.lambdafiles }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: npm i
        
      - name: Build
        run: npm run build

      - name: Move node_modules to dist
        run: mv node_modules dist/node_modules

      - name: Zip
        run: (cd dist && zip -r ../${{ matrix.lambdafiles }}Lambda.zip ${{ matrix.lambdafiles }}Lambda.js)

      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ matrix.lambdafiles }}
          zip_file: ${{ matrix.lambdafiles }}Lambda.zip